### ISSUE TITLE
doesnt work 

### ISSUE THREAD

**Issue by steve55792** [t3rmin8tor/kodi-player-core-factory-install#12] opened 2017-07-30 01:23 UTC
Hi, I had to reinstall windows 10 and i reinstalled the git and kodi-player-core-factory-install. But anyways I tried all 1.8 to 2.2 and i cant get any of them working. I copied the kodi-player-core-factory to the userdata folder in kodi and that worked fine when i played a movie and i hit y to bring out the menu and i click on mpv  the cmd popped up and it clicked back to kodi. The only thing i can do is save the url. Also when i try to record the command report line 97 missing ffmpeg command not found.

**Comment by jaykay0079** [comment] 2017-08-18 01:01
Hi,

I had the same issue after installing Win 10 from scratch. Also getting same error "report line 97 missing ffmpeg command not found" when trying to run it manually.

I downloaded ver1.8 and had to add line to user environment variable  C:%HOMEPATH%\git\kodi-playercorefactory\bash-scripts-windows to get it working but I can not choose record folder path as it puts recording on to desktop by default. 

With ver 1.8 I have to run kodi with admin privilege or else with will come with error permission denied.

**Comment by t3rmin8tor** [comment] 2017-09-01 22:22
hi steve55792 hi jaykay0079 since the last windows 10 updates cycle  there is a problem with file permissions and paths not being set correctly i am currently working on a solution  to these issues 
i am sorry for the bad experiences you both have had

**Comment by Topicform** [comment] 2017-09-06 21:18
Hello T3rmin8tor I am very passionate about your scripts and code, I have easily installed the Rip Records 1.8 file ... all the menus in the codes appear, but at the time of choosing eg Save url or record, or vlc etc ... . nothing is happening. Reload Local Proxy and I can not fix it. I use Krypton 17.4 code on Windows 8.1 64 bit. Thanks for the attention. Hi and good work, you are great and unique. Greetings from Italy.﻿  P.S -   This is my original Enviroment path: C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;%SystemRoot%\system32;

%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program 

Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) 

Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components

\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT﻿

**Comment by t3rmin8tor** [comment] 2017-09-06 23:09
Hi PaoloBordoni1  nice to hear from you  thanks for the raised issue ..... this is the first  one for windows 8.1
i do not see any environment paths for Rip-Record  Cygwin or git 

these should be  
C:\Program Files (x86)\Rip-Record\Cygwin\bin
C:\Program Files (x86)\Rip-Record\bin
C:\Program Files (x86)\Rip-Record\Git\cmd
C:\Program Files (x86)\Rip-Record\Git\bin
%userprofile%\git\kodiplayercorefactiry\bash-scripts\windows;
       
to add these paths to your environment 

open a command prompt and copy the text between   the arrows on one complete line 
then press enter /return
      >>>>>>>

setx PATH ";C:\Program Files (x86)\Rip-Record\Cygwin\bin;C:\Program Files (x86)\Rip-Record\bin;C:\Program Files (x86)\Rip-Record\Git\cmd;C:\Program Files (x86)\Rip-Record\Git\bin;%userprofile%\git\kodiplayercorefactiry\bash-scripts\windows;"

<<<<<<<< 


i hope this  solves your problem

**Comment by steve55792** [comment] 2017-09-07 06:12
to solve the  issues windows 10 having with your program, what if i used  system restore beore the windows cycle update, would that work?

**Comment by t3rmin8tor** [comment] 2017-09-07 08:10
hi steve unfortunately and from experience  i have found that windows restore will not resolve this issue 

the reason being is  while sys retore is good for  correcting user file issues etc it isnt capable of rolling back to a previous build of windows 10 

to update on the solution i will be releasing version 3 of rip-record later today which i have been testing for the past week i am pleased to state that  at pressent i have not found any issues (as yet)  version 3 does solve access permissions as i have removed rip-record from program files which is the problem source  rip-record will now be standalone  in C:\Rip-Record  with all needed environment paths ammended to avoid any windows  complaining about needing permission from system or UAC which has in my perosnal and proffessiona oppinion become  far too aggressive  i am of the mind that microsoft have ignored   the principle of " Personal Computer"   windows 10 for certain does not feel "personal" to me anymore 

again i am sorry you have had a really bad experience with  the software / windows

**Comment by Topicform** [comment] 2017-09-07 09:14
Et Voilà... Hello dear T3rmin8tor, you're as precious as hihihi weights ... It works wonderfully. I added the line; C: \ Program Files (x86) \ VideoLAN \ VLC, and now it's really the Top. I'm waiting for a new version, the 3 ... Maestro thanks and resent soon. Paul.

**Comment by t3rmin8tor** [comment] 2017-09-07 09:53
hi paul  good to know  you are able to use Rip-Record again  if you need further assistance just drop me a message thanks for raising the issue

**Comment by Topicform** [comment] 2017-09-07 09:56
KK and thank for your kindness... see you soon. Hi.

**Comment by steve55792** [comment] 2017-09-07 10:22
Thank you t3rmin8tor, can not wait till the new version. I'm wondering, I tried using ubuntu mate with NapoleonWilson 's and Im having the same problems with it, im wondering if ubuntu mate is having the same issues as windows 10 has? Maybe his rip-record should be seperated(standalone) also.  Just a thought.

**Comment by t3rmin8tor** [comment] 2017-09-07 11:46
hi steve i have  written patches for versions 1.8 2.0 and 2.2 
my suggestion  would be to clear out  any rip-record instalation you have installed 
start with v 1.8  install and then apply the patch depending on your os  be sure to use  the 32 bit patch if the system is not 64  or  just use the 1.8 patch,bat if your os is 64 bit

**Comment by steve55792** [comment] 2017-09-07 13:23
Hi, you mentioned to backup the old path of windows, what would be an easy quick way? I was thinking the backup that windows has.

**Comment by t3rmin8tor** [comment] 2017-09-07 13:38
hi steve  the easiest way is to 
1 open file browser 
2 right  click on This pc
3 select properties
4 select advanced system settings
5 select environment variables
5 select path from user variables so that it is highlighted in blue
6 select edit
7 copy all data in variable value and save it as a txt file  on desktop as path_back_up.txt

this is assuming  there is a path option in user variables 
if there is not  you can simply install rip-record and apply the patch

**Comment by steve55792** [comment] 2017-09-07 14:10
How do you apply the patch after installing install rip-record?

**Comment by t3rmin8tor** [comment] 2017-09-07 14:35
simply double click the patch .bat file  and follow the prompts

**Comment by steve55792** [comment] 2017-09-07 15:07
thats it? just type y or n for yes/no and it will do the rest

**Comment by t3rmin8tor** [comment] 2017-09-07 15:11
hi steve yes  just type y to install the patch

**Comment by steve55792** [comment] 2017-09-07 15:15
that was easy, now gotta play with it and see if it works. And for NapoleonWilson's  rip-record for ubuntu, i dont know what happened but its working now in ubuntu. weird.

**Comment by t3rmin8tor** [comment] 2017-09-07 15:19
hopefully  the issue should be resolved now

**Comment by steve55792** [comment] 2017-09-07 15:28
yes, darn windows operating system, my opinion anything after xp actually after windows 7, it sucks.

**Comment by t3rmin8tor** [comment] 2017-09-07 15:37
i agree windows 7 was a nice system  xp was easy to use  ok it had a few driver issues but it was stable 
microsoft kinda lost their way with windows 8 onwards  as for 10  the new updates  remind me of what some linux distros did to restrict root access  the concept of PERSONAL has been lost

**Comment by steve55792** [comment] 2017-09-07 16:34
It didnt work, it said windows cant find bash

**Comment by t3rmin8tor** [comment] 2017-09-07 17:54
can you paste me the exact command line output  please 

also  you are  just running the install with the default install path ? 
because  if the install path is changed from the default  the install will fail unless you manually edit the paths in environment settings

**Comment by Topicform** [comment] 2017-09-07 21:28
Hi T3rmin8tor, I'm happy since you helped me with Rip-Record .... The wonderful thing is to be able to record streams in AceStream using VLC in the drop down ... the flow is stable and I can record it with VLC, Code could not, because YouTube-DL is not there ... Thank you again, I am having a world of fun. Hello.

**Comment by steve55792** [comment] 2017-09-08 01:10
Windows cant find bash, make sure you typed name correctly, and try again

**Comment by steve55792** [comment] 2017-09-08 01:12
What i did is unistall the first one i had and installed the new one then installed the bat file. that is what i done.

**Comment by steve55792** [comment] 2017-09-08 01:15
i didnt edit no path

**Comment by t3rmin8tor** [comment] 2017-09-08 09:55
hi steve im trying to figure out what the issue is  
where on your system have you installed Rip-Record ? 
the full path could help me figure out a solution 
it should be:

 C:\Program Files (x86)\Rip-Record for 64bit
and patch file  rip-record-v1.8-patch.bat
or
C:\Program Files\Rip-Record for 32bit 
and patch file rip-record-v1.8-32bit-patch.bat

however  if you need  Rip-Record  installed in a different location eg an external drive 
you would need a custom patch file  to  set the environment paths to  the new location

if this is the case if you can give me  the location on the system where you need  Rip-Record installed  i can write a patch file  for you

**Comment by steve55792** [comment] 2017-09-08 10:21
I installed it in the program files but the patch  file rip-record is on the desktop. Being on the desktop(Bat file) would that cause the issues?

**Comment by t3rmin8tor** [comment] 2017-09-08 10:35
hi steve  found the issue  in the patch file  have  fixed  the problem please  re download the patch and re run it should now solve the problems

**Comment by steve55792** [comment] 2017-09-08 11:13
I downloaded it to program file folder and i folled directions and it did the same but windows cant find bash did not pop up. so no luck yet.

**Comment by t3rmin8tor** [comment] 2017-09-08 11:35
that is  weird 

can you do  this 

1 open file explorer 
2 select C Drive 
3 in the search box on the top right where it says search c drive  type in bash 

let me know the results and paths

**Comment by steve55792** [comment] 2017-09-08 11:50
Lol, still waiting, windows 10 soooooooo slow lol.

**Comment by steve55792** [comment] 2017-09-08 11:58
It did not download to c drive. The only one showed up is the ones i did yesterday of installing. should i unistall everything and reinstall everything?

**Comment by t3rmin8tor** [comment] 2017-09-08 12:10
yes  clear out  everything

**Comment by steve55792** [comment] 2017-09-08 12:25
should i downlaod rip-record and bat file seperately or download one whole file like in github.

**Comment by t3rmin8tor** [comment] 2017-09-08 12:32
better to  download the  rip-record installer and  patch file seperately 
just be sure to download the patch that does not  have 32 in the  file name  if using 64 bit

**Comment by steve55792** [comment] 2017-09-08 12:51
Its not working yet. Rip-record is in program files folder. The bat file is on the desktop. for some reason i cant download the bat file, but i copied it in a text file and made it into a bat file., on the desktop. You dont think its a kodi 17.4 would cause the issue?

**Comment by steve55792** [comment] 2017-09-08 12:59
I dont know what i'm doing wrong here, do you use teamviewer?

**Comment by t3rmin8tor** [comment] 2017-09-08 13:02
its not  going to be a kodi 17 issue 

inside rip-record folder are 2 files  
gitconfig.bat
and
continue-install.bat 

first run the gitconfig.bat 
then run the continue-install.bat 

see if  that changes anything

**Comment by t3rmin8tor** [comment] 2017-09-08 13:04
no  i dont use teamviewer

**Comment by steve55792** [comment] 2017-09-08 13:25
i did the 2 bat file and that did not work  but it happened so fast with a command prompt, it said something like fatal error. hat if i tried the 2.0 or 2.2?

**Comment by steve55792** [comment] 2017-09-08 13:34
and if i remember it said something about the directory. the command prompt  went so fast i could not get all the information.

**Comment by t3rmin8tor** [comment] 2017-09-08 14:34
hi steve  i have just ran the installs for 1.8 2.0 and 2.2   2.2 still has issues  but 1.8 and  2.0 installed fine

**Comment by t3rmin8tor** [comment] 2017-09-08 14:46
i suspect the issue was on  gitconfig.bat  sometimes it cant access continue-install.bat  because windows UAC locks it out 
running continue-install.bat should have made git pull the repo files from NapoleonWils0n's repo

**Comment by Topicform** [comment] 2017-09-08 14:53
Hi T3rmin8tor, Rip-Record 2.0 is so fine and You are a big Boss. I wait the
release 3. One word... Amazon work.
Paolo

Il 08/set/2017 16:46, "t3rmin8tor" <notifications@github.com> ha scritto:

**Comment by steve55792** [comment] 2017-09-08 15:10
I'm gonna try 2.0 and see if that works for me. i wonder if unistall 1.8 to install 2.0 or will it just upgrade it.

**Comment by steve55792** [comment] 2017-09-08 15:16
anyways how does a person unlocks the UAC  in Windows?

**Comment by steve55792** [comment] 2017-09-08 15:43
Hi Paolo, did you say that your 2.0 is working fine?

**Comment by Topicform** [comment] 2017-09-08 15:50
Is work in fine?... I say... Super work in fine, I'm so gladiatore of
Rip-record.

Paolo

Il 08/set/2017 17:43, "steve55792" <notifications@github.com> ha scritto:

Hi Paolo, did you say that your 2.0 is working fine?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/t3rmin8tor/kodi-player-core-factory-install/issues/12#issuecomment-328139593>,
or mute the thread

**Comment by steve55792** [comment] 2017-09-08 16:03
did you just download 2.0 and it all works? I'm trying to get 1.8 or 2.0 working on mine but nothing is happening, when i try it , it just kick me back to kodi, cant even save an url.

**Comment by Topicform** [comment] 2017-09-09 21:36
Hi T3rmin8tor, I hope you can help me. I have installed Rip-Records in the program dir (86), and so far all right.
After saving the Video Url file I can not get in CMD to get Bash commands ... which exact path should i get? You're in the video you're in the Desktop directory ... Thanks for the attention. Hi T3rmin8tor..
Paul.

**Comment by t3rmin8tor** [comment] 2017-09-09 21:44
hi paul
do you mean that you  cant use  the command  bash rip-record ?
or  you can not get to the command line ?

**Comment by Topicform** [comment] 2017-09-09 21:48
Hi and thanks for the speed in answering. So that means CMD replies that it fails to recognize the BASH command, maybe because it typed in the wrong dir? What do you say?

**Comment by t3rmin8tor** [comment] 2017-09-09 21:53
ok when you open the cmd promp you need to cd Desktop
then enter the command bash rip-record videofilename.txt -t  00:00:00  < whatever duration yo want to record for 

if  you still have a problem can you paste me the exact  output of the cmd line

**Comment by Topicform** [comment] 2017-09-09 22:03
I tried as you say but without any results. Output says this: Desktop> bash rip-record miley cyrus.txt -t 00:00:00
(http | https | rtmp | rtmpe): //example.com/video-url] ([-t] [00:00:00])

**Comment by t3rmin8tor** [comment] 2017-09-09 22:10
hi paul  thats not a bash issue as  rip-record is responding  but  you need to specify a duration  
so if i want to record for 1 hour  i would  use 

bash rip-record miley-cyrus.txt -t 01:00:00  

but if you know exactly how long the  video file is  you can enter  the exact time  
rip-record will return an error if  the time entered is -t 00:00:00

**Comment by Topicform** [comment] 2017-09-09 22:11
Even if I can not record from command line, I can always do this with VLC from menu in KODI by typing the Y key.

**Comment by t3rmin8tor** [comment] 2017-09-09 22:13
yes but to use the command line  you  must specify a duration as shown above 

if i want to record for 10 mins  i would use  -t 00:10:00

**Comment by Topicform** [comment] 2017-09-09 22:15
Sure. But the video in question lasts about 4 minutes at the end of the line I wrote 00:03:00 ... but it does not work. I hope I will not make any mistakes. Mah?

**Comment by Topicform** [comment] 2017-09-09 22:16
C:\Users\paolo_000\Desktop>bash rip-record milei cyrus.txt -t 00:03:00
Usage: rip-record [(http|https|rtmp|rtmpe)://example.com/video-url] ([-t] [00:00:00])... Ora l'Output è questo, e non funziona !!

**Comment by t3rmin8tor** [comment] 2017-09-09 22:17
hi paul is  sounds like the video file url is not compatable  with  rip-record

**Comment by Topicform** [comment] 2017-09-09 22:19
NO, what a misfortune .... but Nilei Cyrus's file is a music video, do you understand?

**Comment by t3rmin8tor** [comment] 2017-09-09 22:20
yes  but if the  url in the files isnt  one that rip-record can recognise it  will return an error   that  problem is not one that we can fix

**Comment by Topicform** [comment] 2017-09-09 22:21
The Cyrus file I took from an Addon of music videos, not just radio-type music.

**Comment by Topicform** [comment] 2017-09-09 22:22
Ok T3rmin8tor..... now I get it

**Comment by t3rmin8tor** [comment] 2017-09-09 22:22
it may be possible to save the video with vlc  pr mpv player

**Comment by Topicform** [comment] 2017-09-09 22:24
Of course, with vlc or Mpv everything ok !! What are the files I can record, for example, with the Bash rip-record command?

**Comment by NapoleonWils0n** [comment] 2017-09-09 22:25
hi paolo

i think the music addons urls may be different from the video url

your bash command to record looks correct

could you post the url you saved from the music addon and ill see what the issue is

**Comment by Topicform** [comment] 2017-09-09 22:27
Hi Napoleon, this is the file of Milei Cyrus:  https://r6---sn-fpoq-ugoe.googlevideo.com/videoplayback?ip=151.32.73.217&source=youtube&gcr=it&requiressl=yes&mime=video/mp4&expire=1505015629&ratebypass=yes&lmt=1503519325441891&ipbits=0&mm=31&mn=sn-fpoq-ugoe&pl=16&sparams=dur,ei,gcr,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pcm2cms,pl,ratebypass,requiressl,source,expire&id=o-AG1BuFzpwcyksFFgoTLXDZ1ouOCfzFl9p4dhd-5BVqER&mt=1504993918&mv=m&dur=242.300&initcwndbps=651250&itag=22&ms=au&pcm2cms=yes&key=yt6&ei=7WK0Wcr0E869cLvJqoAP&signature=B4106D83CA5463AEB30511FB125408144B86460D.B1921C3B2C4454D7FDD7A55F64A170D9E703ADB9

**Comment by Topicform** [comment] 2017-09-09 22:28
If you click in this file, Goggle open

**Comment by NapoleonWils0n** [comment] 2017-09-09 22:38
hi mate

i just tried recording that url with rip-record and didnt work
i also tried using using youtube-dl and that didnt work either

you could try using firefox with the video download helper

https://addons.mozilla.org/en-GB/firefox/addon/video-downloadhelper/

**Comment by Topicform** [comment] 2017-09-09 22:39
Of course Jack ... I have no problem with what you say, I use Vlc for example and register what I want.

**Comment by Topicform** [comment] 2017-09-09 22:42
For example, this video-url is an Acestream .... how do I transform it to see it on the Addon Plexus, it is just to see the Ace streams in the Code ... eg: acestream: // fghiufghdfghfdgh

**Comment by Topicform** [comment] 2017-09-09 22:42
http://127.0.0.1:6878/content/dd6380def29323a0995809cc29a1202222a0ce58/0.337332891922   ---    This is an ACESTREAM

**Comment by NapoleonWils0n** [comment] 2017-09-09 22:48
hi mate

the scripts dont revord acestream but

i think there is a setting in the acestream app 
that lets you automatically record acestreams as you watch them

if you go into the acestream addon setting i think there is somewhere where you can select a folder to record to
and to auto record any acestream you watch

you could also try opening the acestream link with vlc and try recording with vlc

**Comment by Topicform** [comment] 2017-09-09 22:54
For example this is an acestream link --  acestream://7620c3b34add0772d9b7fe9011aa86bde201c0ba it's ok
This an acestream from save video url in KODI   -   http://127.0.0.1:6878/content/dd6380def29323a0995809cc29a1202222a0ce58/0.337332891922... Different true? I can to transform this HTTP in ace ??

**Comment by Topicform** [comment] 2017-09-09 22:59
Jack, how can I have the menu in KODI even the Pastebin etc ... ??? Thank you.

**Comment by NapoleonWils0n** [comment] 2017-09-09 23:11
hi mate

didnt mean you should try and pastebin the kodi menu

i may be wrong but i think in one of the old acestream addons you could record
they may have removed the option in the new addon

only other thing you could try is opening the acestream with vlc and use that to record

**Comment by Topicform** [comment] 2017-09-09 23:13
Of course, Jack, I'm going to bed now, in Italy are at 01:00 ... where are you from?

**Comment by Topicform** [comment] 2017-09-09 23:20
Hi Jack, this is my Home in KODI. Do you like?
![cattura 2](https://user-images.githubusercontent.com/31699241/30244814-3627428e-95c6-11e7-8cb2-3ffc0d557fbe.PNG)

**Comment by NapoleonWils0n** [comment] 2017-09-09 23:23
hi mate 

very nice kodi screen

im in london uk
about 1 hour behind your time

**Comment by Topicform** [comment] 2017-09-09 23:23
This is magic.... thank you so much Jack & T3rmin8tor :)
![cattura](https://user-images.githubusercontent.com/31699241/30244822-93d114be-95c6-11e7-87d1-ecf4e80fce39.PNG)

**Comment by Topicform** [comment] 2017-09-09 23:24
Ok mate, see you soon... W the Script ahahahaha.... Goodnight :)

**Comment by NapoleonWils0n** [comment] 2017-09-09 23:34
hi mate

happy to help

glad you managed to record the video in the end  
all the best

**Comment by Topicform** [comment] 2017-09-09 23:36
:) ♫ Thank you so much Iack... see you soon !

**Comment by steve55792** [comment] 2017-09-11 01:10
in windows 10 is ffmpeg supposed to be 3.3.3 because mine 3.2.2

**Comment by t3rmin8tor** [comment] 2017-09-11 09:30
hi steve the new version is 3.3.3 but  rip-record  has 3.2.2 
which is  why  rip-record v3 is being built 
v3  will also have a gui for  rip-record  allowing you to 
record  just by entering the file / url and duration
and also allow scheduled recordings

**Comment by Topicform** [comment] 2017-09-11 09:32
Hi Steve, T3rmin8tor and Jack :)

**Comment by steve55792** [comment] 2017-09-11 11:11
Hi PaoloBordoni1, T3rmin8tor and Jack

**Comment by steve55792** [comment] 2017-09-11 11:15
Hi T3rmin8tor is the new version available and should I unistall the old version then install the new version or just install it over the old version?

**Comment by Topicform** [comment] 2017-09-11 11:21
Hi T3rmin8tor, sorry....  When will Rip-Record version 3 be ready? Thanks and good job :)

**Comment by t3rmin8tor** [comment] 2017-09-11 11:23
hi steve  hi paul v3 isnt released yet  still working on it hope fully  i will be able to release it in a couple of days

**Comment by Topicform** [comment] 2017-09-11 11:26
My compliments Teacher .... put as much time as you want, I'm still waiting, thank you again for what you do. Have a nice day dude :)

**Comment by steve55792** [comment] 2017-09-11 11:27
Hi T3rmin8tor, Ok, sounds good, Im gonna use NapoleonWilson version of it until its available, keep up the good work.

**Comment by Topicform** [comment] 2017-09-11 11:31
Hi T3rmin8tor, at this point you have to absolutely change the name of the post up: Doesnt Work, you have to write down Working Fine .... Ahahahah do you believe?

**Comment by steve55792** [comment] 2017-09-11 11:36
Actually its from me PaoloBordoni1, Lol. Mine in windows 10 doesnt work for some reason(I screwed it up somehow). Lol.

**Comment by Topicform** [comment] 2017-09-11 11:36
T3rmin8tor curiosity, when was the Rip-Record project born and when was the first release released? Thank you.

**Comment by Topicform** [comment] 2017-09-11 11:37
I understand Steve, ok Lol :D

**Comment by t3rmin8tor** [comment] 2017-09-11 12:35
hi paul the first ever  release  of rip-record for windows  was version 1 in nov 2016 which is obviously now obsolete  the installer was not automated each part had to be manually configured by the user  
1 configure Cygwin
2 configure git 
3 configure VLC
4 run a config script to set environment paths

version 1.8 was the first fully automated installer 

the installer was based  on the scripts written by NapoleonWils0n which at the time  required the user manually download and setup everything  that was needed

**Comment by steve55792** [comment] 2017-09-11 13:44
Yep, I remember that one, took awhile to set it up.

**Comment by Topicform** [comment] 2017-09-11 20:39
Ok thanks T3rmin8tor is now clear, now it's all automated and works very well. Greetings friend.

**Comment by t3rmin8tor** [comment] 2017-09-11 21:21
yw paul

**Comment by steve55792** [comment] 2017-09-13 07:08
I wonder if I install it the old fashion way it'll work for me. I don't know what went wrong.

**Comment by t3rmin8tor** [comment] 2017-09-13 09:01
hi steve  that my friend is a good idea because it will  either
1 confirm a windows issue
2 confirm a rip-record installer issue

**Comment by steve55792** [comment] 2017-09-13 22:35
How is the new version coming along t3rmin8tor?

**Comment by Topicform** [comment] 2017-09-13 22:41
Hi mate, it's all ok?

**Comment by steve55792** [comment] 2017-09-13 23:18
Is there a download link?

**Comment by steve55792** [comment] 2017-09-14 08:37
is it availble yet?

**Comment by steve55792** [comment] 2017-09-14 09:43
Hi, t3rmin8tor, I think why Im having so much issues here, is that when i missed arounf with the environmental variables. Is there away to get the windows 10 environmental variables back cause the one i supposed to save for backup got deleted. (this is when i was trying the .bat files)

**Comment by t3rmin8tor** [comment] 2017-09-14 11:26
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\

just copy this path and paste it to your system varables path environment variable.

NOT USER VARIABLES

**Comment by steve55792** [comment] 2017-09-14 11:31
now, i'm gonna reinstall rip-record 1.8 and the bat file to see if it works.

**Comment by steve55792** [comment] 2017-09-14 11:32
unless the new version is out already.

**Comment by Topicform** [comment] 2017-09-14 11:37
Hi T3rmin8tor, is there a way to extract an IPTV list from a KODI Addon? Thank you so much :)

**Comment by t3rmin8tor** [comment] 2017-09-14 11:51
Hi paul  i honestly dont know  the best  person to ask would be jack

**Comment by Topicform** [comment] 2017-09-14 11:54
Ok T3rmin8tor... thank you, i ask Jack!

**Comment by t3rmin8tor** [comment] 2017-09-14 11:54
hi steve  no v3 isnt available yey still have  minor bugs to fix

**Comment by steve55792** [comment] 2017-09-14 11:58
ok thanks t3rmin8tor for the info.

**Comment by steve55792** [comment] 2017-09-15 00:11
Hi t3rmin8tor; I reinstalled Windows 10 and rip-record 1.8 w/patch and it grabbed NapoleonWilson  files automatically so that good, but when i clicked on y in the menu to try to record and try mpv player also and it said bash no such directory than it quits and go back to kodi. Rip-record is in the program file section and patch is in on the desktop.

**Comment by steve55792** [comment] 2017-09-15 07:30
Hi, T3rmin8tor

       I updated to 2.0 and everything is working now, I should not be complaining at least its working, LOL, but when i click on record in the command prompt it shows up half the page of permission denied then it finally records, weird huh. I went to the temp folder in the rip-record folder and click  on allow permission.

**Comment by steve55792** [comment] 2017-09-16 12:02
how does the rip-at.exe work, dooes it work with any IPTV.?

**Comment by t3rmin8tor** [comment] 2017-09-16 12:15
hi steve  in theory  as long as you enter  either  the saved txt file name 
or  the full url or the stream 

eg chann  video-file-xx-xx-xx-xx-xx-xx  
then 
duration  00:00:59 for exmple 
 or 
chan  http://whatever-the-url-address-is
duration 00:00:59 

as long as  rip-record can understand the link and the link isnt using f4mproxy it should work exactly as the command line does 

so the format is 

chann name  file  or url
date to record  <-- the date you want to record on 
start time        < -- the time you want to start  recording 
duration  00:00:00 <-- however long u want to record for

**Comment by steve55792** [comment] 2017-09-16 12:35
Interesting, im gonna play with it and see how it works.

**Comment by steve55792** [comment] 2017-09-16 13:10
would this work:

http://smashtv.ddns.net:9090/load/f05998e175bc/6873.mpegts
09/16/2017
8:20
00:05:00

**Comment by steve55792** [comment] 2017-09-16 13:26
I try to find out the errors because i know it did not work but anyways the command prompt open and closed so quickly i could not capture what message pop up.I'm gonna gonna stay with the old way.

**Comment by steve55792** [comment] 2017-09-21 02:12
Hi tr3min8tor, I switched back windows 7 because Windows 10 needed 3 gb ram to run with kodi and it really ran slow and lag alot with windows 10. But anyways I am not sure but would this work windows 7 the same way as it did with windows 10?

**Comment by t3rmin8tor** [comment] 2017-09-21 09:16
hi steve  yes probably better as windows 7 needs less memory

**Comment by steve55792** [comment] 2017-09-21 18:30
How is the new version coming?

almost there steve   just a few dents to get  rid of :)

**Comment by Topicform** [comment] 2017-09-27 21:32
Hey guys, hello Jack & T3rmin8tor all right? .. I hope so .... News?

**Comment by t3rmin8tor** [comment] 2017-09-27 21:39
hi paul  how are you  we are just  ironing out a few bugs fir the new release which should be completed within an hour or 2

**Comment by steve55792** [comment] 2017-09-27 22:02
cool, cant wait to try it out.

**Comment by Topicform** [comment] 2017-09-27 22:42
Thank you so much T3rmin8tor, fantastic news from You, i wait :)

Paolo

**Comment by steve55792** [comment] 2017-09-28 18:51
Hi t3rmn8tor, hows it going for you? Did you finish ironing out the bugs on the new release?

**Comment by t3rmin8tor** [comment] 2017-09-28 19:57
hi steve  yes compiling  the installer  as we speak

**Comment by steve55792** [comment] 2017-09-28 20:49
sweet, cant wai t to try it.

**Comment by t3rmin8tor** [comment] 2017-09-29 00:52
hi paul  hi steve  

new release is out  be sure to completely uninstall rip-record before installing 

https://github.com/t3rmin8tor/pilfer-installer/blob/master/README.md

**Comment by steve55792** [comment] 2017-09-29 01:50
I installed it, anything else we gotta setup inside the program?

**Comment by steve55792** [comment] 2017-09-29 03:26
It says windows cant find bash, okay what did i do wrong here?

hi steve  pilfer does not use bash 
the new command line   is  just
pilfer -i filename.txt -t 

the gui  called pilfer (shortcut on desktop)  is the best way  to use the program on windows

**Comment by Topicform** [comment] 2017-09-29 09:36
Hello T3rmin8tor, I'm confused, sorry, what does PILFER mean? ... I was thinking of finding a file named Rip-Records .... thanks for the attention. I Try the file and then I'll tell you. Thank you 1000.

**Comment by Topicform** [comment] 2017-09-29 09:57
Hello T3rmin8tor, I uninstall Rip Records ... the menu by typing in KODI the Y has remained. Maybe you have to change the environment variable? .... Sorry but I do not know what to do !! Thank you.

**Comment by t3rmin8tor** [comment] 2017-09-29 10:00
hi paul  thanks for the info  it seems  that  the playercorefactory.xml is not being created in kodi properly
i will fix this issue as soon as possible

**Comment by Topicform** [comment] 2017-09-29 10:04
Ok... I wait... Thank you so much and good job :)

**Comment by t3rmin8tor** [comment] 2017-09-29 10:06
hi paul  copy  this  file  into kodi\userdata 

https://github.com/NapoleonWils0n/pilfer/blob/master/playercorefactory/windows/playercorefactory.xml

hopefully it will fix the problem

**Comment by steve55792** [comment] 2017-09-29 10:33
I unistalled the pilfer and reinstalled it. so hoping it will work for me. I copied the playercorefactory.xml also into kodi cause i see paul was having issue also.  All we do is play kodi and when a movies click on menu or y then click record or mpv or whatever?

**Comment by Topicform** [comment] 2017-09-29 10:39
So ... For the moment back to the record 2.2 ... I'm looking for new developments ... The Pilfer has trouble for me now .... Thanks for the attention, I'm waiting.

**Comment by steve55792** [comment] 2017-09-29 10:44
Hi, PaoloBordoni, What kind of issues were you having? When i tried it , after the movie was playing I clicked on Y nd it hit record/save url the command prompt flashed nd then quit, and it didnt save anything. I probably go back to record 2.2 also until the issues is fixed. There is probably a bug somewhere, I give tr3mn8tor alot of credit for all the hard work he is putting out on this programs.

**Comment by t3rmin8tor** [comment] 2017-09-29 10:45
hi paul hi steve i have fixed the issue  please re download  the installer and run  there is no need to uninstall
as the installer will just update  the files 
i have also updated the readme 
https://github.com/t3rmin8tor/pilfer-installer/blob/master/README.md

**Comment by steve55792** [comment] 2017-09-29 10:46
Lol, I just unistalled it.

**Comment by Topicform** [comment] 2017-09-29 10:46
Ok Mate, i try... stay tuned :)

**Comment by steve55792** [comment] 2017-09-29 10:50
Hi tr3min8tor, do we have to reinstall playercorefactory.xml again, or is automatically do it for us?

**Comment by t3rmin8tor** [comment] 2017-09-29 10:55
no steve   that issue has been fixed  all you have to do is run the installer

**Comment by Topicform** [comment] 2017-09-29 11:00
You are right T3rmin8tor, the Playercorefactory file has been updated .... But I was used to seeing in the Y menu the voice VLC etc .... now i am not in, my environment variable is that with Rip Records ... no I would confuse ... but I have problems .... Sorry and thank you.

**Comment by steve55792** [comment] 2017-09-29 11:12
ok, when i tried it with kodi, yes the playercorefactory showed up when i clicked on y,  when i clicked on record, command prompt showed up quickly and everything stopped. i looked on the desktop for an saved url or the start of a recording, nothing showed up.

**Comment by t3rmin8tor** [comment] 2017-09-29 11:37
hi steve hi paul  i really apreciate your  feedback 
i believe i have found the issues  give me 20 mins i need a bigger fly swatter 
im sure you can apreciate  that  some  operating systems  have different methods of doing things
(eg windows 7 and 8 use a different syntax to windows 10 )

**Comment by steve55792** [comment] 2017-09-29 11:51
I went back to windows 7, what operating system do you have Paul?

**Comment by Topicform** [comment] 2017-09-29 12:08
I have Windows 8. 1 64bit
Paolo

**Comment by Topicform** [comment] 2017-10-01 18:34
Hello T3min8tor, a question: When you save in Code
the file with Save url file, can you get the file link in clear without the% and other symbols that make it difficult to decipher exactly the Link? for example this: http://127.0.0.1:55333/callbackpath=&use_proxy_for_chunks=True&streamtype=TSDOWNLOADER&maxbitrate=0&proxy=None&callbackparam=&url=http%3A%2F%2F163.172.52.83%3A8000%2Flive%2F303040977B03cC%2F040007400Y4282%2F380. ts & swf = None & auth = & simpledownloader = False. I managed to make it legible, replacing the% with the sign: etc ... In summary you can have the link like this ... http://163.172.52.83:8000/live/303040977B03cC/040007400Y4282/380.ts. Thank you for your attention and tons of thanks to your genius.

**Comment by NapoleonWils0n** [comment] 2017-10-01 20:01
hi paolo 

when you save the url from kodi it is saved as is
thats just what those urls look like

those kinds of url are ones that use a local proxy
and url encode the url to replace characters like space with %20

you can use an online url decoder to decode the url

https://www.urldecoder.org

you can also write python scripts to decode the url
but youll probably find it quicker to just use an online url decoder

**Comment by Topicform** [comment] 2017-10-01 22:19
Thank you so much for your precious idea... Thank you again Jack :)
Paolo

Il 01/ott/2017 22:01, "NapoleonWils0n" <notifications@github.com> ha
scritto:

**Comment by Topicform** [comment] 2017-10-02 10:37
Hello Napoleon, I pay close attention to your work, and in my opinion you
are a nice kind person and prepared for the matter. I ask you a question:
When I save in Code with the command Save Video url after a moment the
channel stops and the file is saved on the Desktop, and it's okay. Could
you prevent the video from interrupting?

2017-10-02 0:19 GMT+02:00 Paolo Bordoni <paolobordoni1@gmail.com>:

**Comment by NapoleonWils0n** [comment] 2017-10-02 13:07
hi paolo

the menu i use to save the url from kodi is used to open the video links in an external player like mpv

i just created a "player" that saves the url instead of playing it

obviously if you  are opening the url in another video player the video in kodi wouldnt keep playing
that wouldnt make sense to have the video playing in kodi and another player at the same time

thats just the way the menu for launching external players works from kodi
so its not something i can change because its built into kodi

**Comment by t3rmin8tor** [comment] 2017-10-02 16:35
i am closing this issue as the thread has gotten too long 
also these issues no longer relate to Rip-Record but pilfer
please  raise issues in the pilfer repo where  we will be happy to
offer assistance

**Closed as completed by t3rmin8tor** 2017-10-02 16:35 UTC
